language: java
jdk:
  - openjdk7
after_success:
  # unpack the key we will need to execute the deployment commands.
  - openssl aes-256-cbc -K $encrypted_8af5c54b98ba_key -iv $encrypted_8af5c54b98ba_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d
  # install the key
  - chmod 600 scripts/id_rsa
  - ssh -oStrictHostKeyChecking=no -l tryopenjml -i scripts/id_rsa openjml.cs.ucf.edu "cd /home/tryopenjml/try-openjml; git pull; mvn compile; killall java"


